#!/bin/env ruby

require_relative 'parser'

input = File.read(ARGV[0])

input.each_line do |line|
  Parser.new(line).call
end

def reset_and_override_b(input, new_b_value)
  input.each_line do |line|
    Parser.new(line).call
  end

  Value.new('b', new_b_value)
end


# $gate_set.each do |k,obj|
#   puts "#{k} == #{obj.call}"
# end

a_value = $gate_set['a'].call

puts "A is: #{a_value}"

reset_and_override_b(input, a_value)

new_a_value = $gate_set['a'].call
puts "New A signal is: #{new_a_value}"