#!/bin/env ruby

require_relative 'deliveries'
require_relative 'deliveries_with_two_santas'

input = File.read(ARGV[0])

puts("Santa only: #{Deliveries.new(input).call}")

puts("Santa & Robo-Santa: #{DeliveriesWithTwoSantas.new(input).call}")