#!/bin/env ruby

require_relative 'floor_walker'

floor_walker = FloorWalker.new(File.read(ARGV[0])).call

puts("Final floor: #{floor_walker.final_floor}")
puts("Position on entering basement: #{floor_walker.position_on_entering_basement}")