#!/bin/env ruby

require_relative 'line_parser'
require_relative 'resource_calculator'

parser = LineParser.new(File.open(ARGV[0]))
wrapping_paper_total = 0
ribbon_total = 0

parser.each do |length, width, height|
  resource_calculator = ResourceCalculator.new(length, width, height).call
  wrapping_paper_total += resource_calculator.wrapping_paper
  ribbon_total += resource_calculator.ribbon
end

puts("Wrapping paper: #{wrapping_paper_total}")
puts("Ribbon: #{ribbon_total}")